### ISSUE TITLE
How to get file path

### ISSUE THREAD

**Issue by wengbenjue** [bamlab/rn-camera-roll#4]
I want get the filepath and upload to my server ,

How can I get this

**Comment by wengbenjue** [comment]
My uri is 'assets-library://asset/asset.JPG?id=ADDB18BD-F81E-4C64-BB05-D994F0D53F8D&ext=JPG' in IOS
How  can I get th real absolute file path

**Comment by 4ian** [comment]
This module is not meant to read files or/and upload them. If you want to do so, you have to use `XMLHttpRequest` and `FormData`: check the examples of React Native. If I remember correctly, for Android this isn't available so you have to rely on an external module like https://github.com/PhilippKrone/react-native-fileupload

**Comment by wengbenjue** [comment]
I have do it ,In Android ,Can get the file:/xxxxx.xx , I hope Ios  can get the absolute filepath and assets tag,both maybe useful,If I uploade by data streaming,It's slow than binary file by IOS

**Comment by wengbenjue** [comment]
Maybe I shoud receive your suggest  for use base64 post,Thanks

**Comment by Almouro** [comment]
@wbj0110 try removing the `file:` suffix from the data returned by `rn-camera-roll` and see if that works (for instance `/storage/emulated/0/DCIM/Camera/IMG_20151126_115520477.jpg`)
