### ISSUE TITLE
> failed to find Build Tools revision 23.0.2

### ISSUE THREAD

**Issue by deju** [bamlab/rn-camera-roll#5]
I got an error like this:

```
deju-pro:JJTest tudeju$ react-native run-android
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
 A problem occurred configuring project ':app'.
> A problem occurred configuring project ':rn-camera-roll'.
 > failed to find Build Tools revision 23.0.2

 * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

 Total time: 9.542 secs
 Could not install the app on the device, read the error above for details.
 Make sure you have an Android emulator running or a device connected and have
 set up your Android development environment:
 https://facebook.github.io/react-native/docs/android-setup.html
```

`A problem occurred configuring project ':rn-camera-roll'.
     > failed to find Build Tools revision 23.0.2`. What does this mean?

In SDK directory, i were find the build-tools version is 23.0.1. Should i download anthor version?

**Comment by 4ian** [comment]
> In SDK directory, i were find the build-tools version is 23.0.1. Should i download anthor version?

As said in the error message, you **must** install Build Tools revision 23.0.**2**, not Build Tools revision 23.0.1 ;)

**Comment by deju** [comment]
@4ian  I tried it. It is OK NOW! Thanks!

**Comment by 4ian** [comment]
Sweet! :+1:

**Comment by AugustoAleGonZhipCode** [comment]
There is no any other way to not installing those tools? and changing the version of the build tool?
